export const GAMES = [
  "Valorant",
  "Fortnite",
  "Apex Legends",
  "Call of Duty",
  "League of Legends",
  "Overwatch 2",
  "CS2",
  "Rust",
  "Minecraft",
  "Destiny 2",
  "GTA Online",
  "Rocket League",
  "Rainbow Six Siege",
  "PUBG",
  "Warframe",
  "Dota 2",
  "Helldivers 2",
  "Baldur's Gate 3",
  "Final Fantasy XIV",
  "World of Warcraft",
] as const;
